name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: ./build.sh
    - uses: actions/upload-artifact@v4
      name: Upload
      with:
        name: ffmpeg
        path: dist/linux/x86_64/ffmpeg/
