name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install nasm
        git clone https://github.com/yasm/yasm.git
        cd yasm
        git checkout v1.3.0
        ./autogen.sh && ./configure && make && make install
    - name: Build
      run: ./build.sh
    - uses: actions/upload-artifact@v4
      name: Upload
      with:
        name: ffmpeg
        path: dist/linux/x86_64/ffmpeg/
